[package]
name = "hello-world-cargo"
version = "0.1.0"
authors = ["lrgCuadrado <luisraul_a@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
